version: '3'
services:
  screw-hand_nginx:
    image: screw-hand_nginx
    container_name: screw-hand_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert/:/cert/
      - /etc/localtime:/etc/localtime
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./blog/:/usr/share/nginx/html/blog/

