name: GitHub Pages

on:
  push:
    branches:
      - hexo

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set Git username and email
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
